version: "3"
services:
  nginx:
    build: .
    ports:
      - 3000:80
    restart: always
    environment:
      - DB_PASS=
      - DB_NAME
      - DB_HOST=mysql
      - STRIPE_API_KEY
      - STRIPE_PUB_KEY
      - SECRET
      - DB_USER=root
      - CLOUD_VISION_API_KEY
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET_KEY
      - TZ=Asia/Tokyo

  mysql:
    image: mysql:5.7
    expose:
      - 3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
