name: Run Unit Tests

on: [pull_request]

jobs:
  check:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10

      stripe-mock:
        image: stripemock/stripe-mock:latest
        ports:
          - 12111:12111

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          yarn install

      - name: Check Lint
        run: |
          yarn lint

      - name: Create Database
        run: |
          mysql -h 127.0.0.1 -u root < ./db/1_create_db.sql

      - name: Run tests
        run: |
          yarn test
        env:
          SECRET: secret
          DB_NAME_TEST: bokin_test_db
          DB_NAME: bokin_db
